#!/bin/bash

# =============================================================================
# ALL MAIL SERVER ADMIN CREDENTIALS
# =============================================================================
# Complete list of admin credentials for all mail services
# =============================================================================

echo "🔐 COMPLETE MAIL SERVER ADMIN CREDENTIALS"
echo "=========================================="
echo ""

echo "🌐 ACCESS URLS:"
echo "==============="
echo "• Mailu Admin: https://mail.soham.top/admin"
echo "• Postal Admin: https://postal.soham.top"
echo "• Mautic Admin: https://mautic.soham.top"
echo ""

echo "📧 MAILU ADMIN CREDENTIALS:"
echo "==========================="
echo "• URL: https://mail.soham.top/admin"
echo "• Email: admin@soham.top"
echo "• Password: Grow@1234"
echo "• Status: ✅ WORKING"
echo ""

echo "📮 POSTAL ADMIN CREDENTIALS:"
echo "============================="
echo "Option 1 (Original Admin):"
echo "• URL: https://postal.soham.top"
echo "• Email: admin@localhost"
echo "• Password: password"
echo "• Status: ✅ UPDATED"
echo ""
echo "Option 2 (Custom Admin):"
echo "• URL: https://postal.soham.top"
echo "• Email: admin@soham.top"
echo "• Password: password"
echo "• Status: ✅ UPDATED"
echo ""

echo "📊 MAUTIC ADMIN CREDENTIALS:"
echo "============================"
echo "• URL: https://mautic.soham.top"
echo "• Username: admin"
echo "• Password: Grow@1234"
echo "• Status: ✅ SHOULD WORK"
echo "• Note: Check initial setup wizard if first login"
echo ""

echo "🗄️ DATABASE ACCESS:"
echo "==================="
echo "MySQL Root Access:"
echo "• Host: localhost:3306 (from mailu containers)"
echo "• User: root"
echo "• Password: Grow@1234"
echo ""
echo "Postal Database:"
echo "• Host: postal-db-1:3306"
echo "• User: root"
echo "• Password: postal_root_password"
echo "• Database: postal"
echo ""

echo "🐳 CONTAINER MANAGEMENT:"
echo "========================"
echo "Restart all services:"
echo "cd /home/ubuntu/ms && docker-compose down && docker-compose up -d"
echo ""
echo "Check service status:"
echo "docker ps | grep -E '(mailu|postal|mautic)'"
echo ""
echo "View logs:"
echo "docker logs mailu-admin-1"
echo "docker logs postal-web-1"
echo "docker logs mautic-web-1"
echo ""

echo "🔧 CREDENTIAL RESET SCRIPTS:"
echo "============================"
echo "Reset Mailu admin:"
echo "docker exec mailu-admin-1 flask mailu admin admin@soham.top Grow@1234"
echo ""
echo "Reset Postal admin (admin@localhost):"
echo "docker exec postal-web-1 bash -c \"echo 'user = User.find_by(email_address: \\\"admin@localhost\\\"); user.password = \\\"password\\\"; user.password_confirmation = \\\"password\\\"; user.save!' | postal console\""
echo ""
echo "Reset Postal admin (admin@soham.top):"
echo "docker exec postal-web-1 bash -c \"echo 'user = User.find_by(email_address: \\\"admin@soham.top\\\"); user.password = \\\"password\\\"; user.password_confirmation = \\\"password\\\"; user.save!' | postal console\""
echo ""

echo "📝 SERVICE STATUS:"
echo "=================="
echo "All services should be accessible at:"
echo "• ✅ https://mail.soham.top (Mailu - Webmail & Admin)"
echo "• ✅ https://postal.soham.top (Postal - Bulk Email)"
echo "• ✅ https://mautic.soham.top (Mautic - Email Marketing)"
echo ""
echo "All configurations are persistent across restarts."
echo "If CSRF errors occur in Postal, clear browser cache/cookies."
echo ""

echo "🚨 QUICK LOGIN TEST:"
echo "===================="
echo "1. Mailu: https://mail.soham.top/admin"
echo "   → admin@soham.top / Grow@1234"
echo ""
echo "2. Postal: https://postal.soham.top"
echo "   → admin@localhost / password"
echo "   → OR admin@soham.top / password"
echo ""
echo "3. Mautic: https://mautic.soham.top"
echo "   → admin / Grow@1234"
echo ""

echo "✨ ALL CREDENTIALS READY FOR USE!"
